
## Original V1 by Ruben ven Helden
## Version 2.0 generated by Ben Johnson

find_peaks <- function (df, x, top = 25, bot = 25, pref = 0.5, mult_n = FALSE){
  
  require(dplyr)
  require(pspline)
  require(tidyverse)
  
  df <- as.data.frame(df)
  res <- data.frame()
  pksNew <- data.frame()
  pksClean <- data.frame()
  
  FUN <- function(i, x, m) {
    z <- i - m + 1
    z <- ifelse(z > 0, z, 1)
    w <- i + m + 1
    w <- ifelse(w < length(x), w, length(x))
    
    if (all(x[c(z : i, (i + 2) : w)] <= x[i + 1]) &&
        all(complete.cases(x[c(z : i, (i + 2) : w)]))) 
      return(i + 1) 
    else 
      return(numeric(0))
  }
  
  shape <- diff(sign(diff(df[, x], na.pad = FALSE)))
  
  # Find peaks
  pks <- sapply(which(shape < 0), FUN, df[, x], top)
  pks <- unlist(pks)
  pks_bord <- df[pks,]
  
  
  shape_low <- diff(sign(diff(-df[, x], na.pad = FALSE)))
  vals <- sapply(which(shape_low < 0), FUN, -df[, x], bot)
  vals <- unlist(vals)
  
  res <- rbind(data.frame(df[pks,], shape = "max"), 
               data.frame(df[vals,], shape = "min")) %>% 
    group_by(Well) %>% filter(!shape == lag(shape, default = first(shape), order_by = Time))
  
  
  for (well_name in unique(res$Well)) {
    subset_data <- df[df$Well == well_name, ]
    subset_data <- subset_data %>% arrange(desc(Smooth))
    subset_data1 <- res[res$Well == well_name, ]
    max_value <- mean(head(subset_data$Smooth, 5))
    min_value <- mean(tail(subset_data$Smooth, 100))
    filter_value <- ((max_value - min_value)*pref)+min_value
    
    subset_data1 <- subset_data1 %>%
      filter(shape == "max") %>%
      filter(Smooth >= (filter_value))
    
    pksNew <- rbind(pksNew, subset_data1)
  }
  pksNew <- rbind(res[!(res$shape == "max"), ], pksNew)
  
  for (well_name in unique(pksNew$Well)) {
    
    subset_data <- pksNew[pksNew$Well == well_name, ]
    subset_data1 <- subset_data %>% arrange(Time) %>%
      mutate(binary = ifelse(shape == "min", 0, ifelse(shape == "max", 1, NA)))
    subset_data1 <- transform(subset_data1, next_binary = c(binary[-1], NA))
    
    subset_data1 <- subset_data1 %>% 
      filter(!(binary == next_binary)) %>%
      select(-binary) %>%
      select(-next_binary)
    
    pksClean <- rbind(pksClean, subset_data1)
  }
  pksClean
}